apiVersion: apps/v1
kind: Deployment
metadata:
  name: Python_flask_app
  labels:
    app: python_flask_app
spec:
  selector:
    matchLabels:
        app: python_flask_app
  replicas: 1
  template:
    metadata:
      labels:
        app: python_flask_app
    spec:
      containers:
        - name: python_flask_app
          image: 921107229751.dkr.ecr.ap-south-1.amazonaws.com/nodeecr:v1
          ports:
            - containerPort: 5000
              protocol: TCP
          imagePullPolicy: Always

